"""updated years column types

Revision ID: 770f5e02ec58
Revises: caa65671a03b
Create Date: 2023-11-13 19:29:02.009173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "770f5e02ec58"
down_revision = "caa65671a03b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analytics", schema=None) as batch_op:
        batch_op.alter_column(
            "end_year",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "start_year",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analytics", schema=None) as batch_op:
        batch_op.alter_column(
            "start_year",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "end_year",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
