"""rename column name

Revision ID: eeb907413006
Revises: c6f2892526b4
Create Date: 2023-11-13 19:24:51.018101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eeb907413006"
down_revision = "c6f2892526b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analytics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("intensity", sa.Integer(), nullable=True))
        batch_op.drop_column("intesity")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("analytics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("intesity", sa.INTEGER(), nullable=True))
        batch_op.drop_column("intensity")

    # ### end Alembic commands ###
